# Generated by Django 3.2 on 2021-05-09 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='has_been_in_mainteance',
            field=models.BooleanField(default=False),
        ),
    ]
